server:
  applicationConnectors:
    - type: http
      port: 7979
  adminConnectors:
    - type: http
      port: 7997
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: password1!
  url: jdbc:mysql://localhost/skeleton
  properties:
    charSet: UTF-8